### ISSUE TITLE
fastANI error loading shared libraries libgsl.so.25

### ISSUE THREAD

**Issue by CaitlinSelway** [lmc297/BTyper3#7]
Hi Laura, 

I was installing this great tool this morning, but came across an error with libgsl.so.25. 
```
$ btyper3 -i 2218710072.fna -o bytper3
Welcome to BTyper3!
You are initializing this run at 2022-07-19 08:56
You ran the following command:
/phe/tools/miniconda3/envs/btyper3/bin/btyper3 -i 2218710072.fna -o bytper3
Report bugs/concerns to Laura M. Carroll, laura.carroll@embl.de
Using FastANI to assign 2218710072 to a species at 2022-07-19 08:56
fastANI: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/phe/tools/miniconda3/envs/btyper3/bin/btyper3", line 10, in <module>
    sys.exit(main())
  File "/phe/tools/miniconda3/envs/btyper3/lib/python3.10/site-packages/btyper3/__init__.py", line 441, in main
    run_pipeline(args)
  File "/phe/tools/miniconda3/envs/btyper3/lib/python3.10/site-packages/btyper3/__init__.py", line 105, in run_pipeline
    final_species = get_species.run_fastani("species", fastani_path, infile, final_results_directory, prefix)
  File "/phe/tools/miniconda3/envs/btyper3/lib/python3.10/site-packages/btyper3/ani.py", line 60, in run_fastani
    proc.check_returncode()
  File "/phe/tools/miniconda3/envs/btyper3/lib/python3.10/subprocess.py", line 456, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['fastANI', '-q', '2218710072.fna', '--rl', '/tmp/tmp69n8g9vktxt', '-o', 'bytper3/btyper3_final_results/species/2218710072_species_fastani.txt']' returned non-zero exit status 127
```

After a quick google, the current gsl version 2.7.1 only provides libgsl.so.27. For anyone else that encounters this issue, I fixed it by downgrading the gsl version from 2.7.1 to 2.7.
`conda install gsl=2.7`

Have a good day! 
Caitlin

**Comment by althonos** [comment]
Hi Caitlin, 
this looks more like a Bioconda issue, I'll be opening an issue there as well, this can likely be fixed by pinning an exact `gsl` version for the `fastani` package (at the moment it expects `gsl>=2.7,<2.8`).

**Comment by althonos** [comment]
Actually, this looks like it was fixed already in bioconda/bioconda-recipes#35517, have you updated your `conda` environment in the last month?
